# Copyright (C) 2018 Juergen Zimmermann, Florian Rusch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
extends: 'eslint:recommended'
env:
    browser: true
    es6: true
parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        impliedStrict: true
rules:
    array-bracket-spacing: error
    array-bracket-newline:
        - error
        - multiline: true
    arrow-body-style:
        - error
        - as-needed
    arrow-parens:
        - error
        - as-needed
    block-scoped-var: error
    block-spacing: error
    camelcase: error
    comma-spacing: error
    comma-style: error
    consistent-this: error
    curly: error
    comma-dangle:
        - error
        - always-multiline
    default-case: error
    dot-notation: error
    eqeqeq: error
    eol-last: error
    for-direction: error
    func-call-spacing: error
    func-name-matching: error
    func-names:
        - error
        - never
    func-style: error
    getter-return: error
    indent:
        - error
        - 4
    init-declarations: error
    key-spacing: error
    keyword-spacing: error
    line-comment-position: error
    linebreak-style:
        - error
        - windows
    max-len:
        - error
        - ignoreComments: true
    no-buffer-constructor: error
    no-duplicate-imports: error
    no-else-return: error
    no-empty-function: error
    no-extra-parens: error
    no-implicit-globals: error
    no-magic-numbers: error
    no-multi-spaces: error
    no-multiple-empty-lines: error
    no-negated-condition: error
    no-param-reassign: error
    no-shadow: error
    no-tabs: error
    no-template-curly-in-string: error
    no-trailing-spaces: error
    no-use-before-define: error
    no-useless-return: error
    no-var: error
    no-whitespace-before-property: error
    nonblock-statement-body-position: error
    object-curly-newline:
        - error
        - ObjectExpression: always
          ObjectPattern:
              multiline: true
    object-property-newline: error
    object-shorthand:
        - error
        - always
    one-var-declaration-per-line: error
    operator-assignment: error
    operator-linebreak: error
    padded-blocks:
        - error
        - never
    prefer-arrow-callback: error
    prefer-const: error
    prefer-destructuring: error
    prefer-numeric-literals: error
    prefer-promise-reject-errors: error
    prefer-rest-params: error
    prefer-spread: error
    prefer-template: error
    quote-props:
        - error
        - as-needed
    quotes:
        - error
        - single
    require-await: error
    rest-spread-spacing: error
    semi:
        - error
        - never
    semi-spacing: error
    sort-imports: error
    space-before-blocks: error
    space-before-function-paren:
        - error
        - never
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment: error
    strict: error
    template-curly-spacing: error
